{
  "id": "CVE-2025-29088",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2025-04-10T14:15:27.163",
  "lastModified": "2025-04-11T20:15:21.553",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "An issue in sqlite v.3.49.0 allows an attacker to cause a denial of service via the SQLITE_DBCONFIG_LOOKASIDE component"
    },
    {
      "lang": "es",
      "value": " Un problema en sqlite v.3.49.0 permite que un atacante provoque una denegación de servicio a través del componente SQLITE_DBCONFIG_LOOKASIDE"
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "attackVector": "NETWORK",
          "attackComplexity": "LOW",
          "privilegesRequired": "NONE",
          "userInteraction": "NONE",
          "scope": "UNCHANGED",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "availabilityImpact": "HIGH",
          "baseScore": 7.5,
          "baseSeverity": "HIGH"
        },
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
      }
    ]
  },
  "weaknesses": [
    {
      "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-400"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://gist.github.com/ylwango613/d3883fb9f6ba8a78086356779ce88248",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/sqlite/sqlite/commit/56d2fd008b108109f489339f5fd55212bb50afd4",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://www.sqlite.org/cves.html",
      "source": "cve@mitre.org"
    }
  ]
}